modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pumpvisuals"
version="1.0.0"
displayName="PumpVisuals"
authors="minefix2025-boop"
description="Pumpkin themed visuals and X-Ray mod."

[[dependencies.pumpvisuals]]
modId="forge"
mandatory=true
versionRange="[36.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.pumpvisuals]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
