modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pumpkinvisuals"
version="1.0.0"
displayName="Pumpkin Visuals"
authors="minefix2025-boop"
description="Мод на визуальные эффекты и X-Ray."

[[dependencies.pumpkinvisuals]]
modId="forge"
mandatory=true
versionRange="[36.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.pumpkinvisuals]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
